import React, { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
import { useNavigate } from "react-router-dom";
import {
  Sparkles,
  Upload,
  FileText,
  AlertTriangle,
  Crown,
  Trash2,
  Printer,
  Clock,
  CheckCircle2,
  Shield,
  Brain,
  Camera,
  X
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Checkbox } from "@/components/ui/checkbox";
import { checkSubscription } from "@/components/utils/subscriptionUtils";
// import { printReport } from "@/components/utils/printHelpers"; // This import is no longer needed
import PaywallModal from "../components/paywall/PaywallModal";
import { format } from "date-fns";

const TENNESSEE_DISCLAIMER = `COMPREHENSIVE LIABILITY DISCLAIMER AND TERMS OF USE

By clicking "I Accept and Proceed," you acknowledge and agree to the following terms under Tennessee State Law:

1. INFORMATIONAL PURPOSES ONLY: All scenario analyses, recommendations, and content generated by this AI tool are provided solely for informational and educational purposes. They do NOT constitute professional advice of any kind.

2. NO PROFESSIONAL RELATIONSHIP: Use of this tool does not create any professional relationship including but not limited to: veterinary, legal, financial, medical, or agricultural advisory relationships.

3. PROFESSIONAL CONSULTATION REQUIRED: You acknowledge that you should consult with appropriate licensed professionals before taking any action based on information provided by this tool.

4. USER RESPONSIBILITY: You accept FULL AND COMPLETE RESPONSIBILITY for any and all actions you take based on information provided by this AI analysis tool. This includes but is not limited to: property damage, personal injury, animal welfare issues, financial losses, legal consequences, or any other claims or damages of any nature.

5. CRIMINAL ACTIVITY WARNING: You acknowledge that this analysis may relate to potentially illegal or harmful activities. You affirm that you will use this information solely for analytical and educational purposes and NOT to engage in any illegal activities.

6. RELEASE OF LIABILITY: You hereby release, waive, discharge, and covenant not to sue Homestead Acres, its owners, operators, developers, and affiliates from any and all liability, claims, demands, actions, and causes of action whatsoever arising out of or related to any loss, damage, or injury that may be sustained by you or any third party in connection with your use of this AI analysis tool.

7. INDEMNIFICATION: You agree to indemnify, defend, and hold harmless Homestead Acres, its owners, operators, developers, and affiliates from any claims, damages, losses, liabilities, and expenses (including attorney fees) arising from your use of this tool or breach of these terms.

8. GOVERNING LAW AND JURISDICTION: This disclaimer and your use of this tool shall be governed by and construed in accordance with the laws of the State of Tennessee, without regard to its conflict of law provisions. You irrevocably consent to the exclusive jurisdiction of the courts located in Tennessee for any disputes arising from or relating to your use of this tool.

9. RECORD RETENTION: Your acceptance of this disclaimer will be recorded and retained for one (1) year for legal compliance purposes, accessible only to system administrators.

10. SEVERABILITY: If any provision of this disclaimer is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that this disclaimer shall otherwise remain in full force and effect.

By accepting these terms, you acknowledge that you have read, understood, and agree to be bound by all provisions of this disclaimer.

Date of Acceptance: ${new Date().toLocaleString()}
Applicable Law: Tennessee State Law`;

export default function AIScenarioAnalysis() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  
  const [showPaywall, setShowPaywall] = useState(false);
  const [title, setTitle] = useState("");
  const [scenario, setScenario] = useState("");
  const [uploadedFiles, setUploadedFiles] = useState([]);
  const [uploading, setUploading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [showWarningDialog, setShowWarningDialog] = useState(false);
  const [pendingAnalysis, setPendingAnalysis] = useState(null);
  const [showDisclaimerDialog, setShowDisclaimerDialog] = useState(false);
  const [disclaimerAccepted, setDisclaimerAccepted] = useState(false);
  const [selectedAnalysis, setSelectedAnalysis] = useState(null);
  const [showFirstTimeDisclaimer, setShowFirstTimeDisclaimer] = useState(false);
  const [hasAcceptedFirstTime, setHasAcceptedFirstTime] = useState(false);

  const { data: subscriptionData } = useQuery({
    queryKey: ['subscription'],
    queryFn: checkSubscription,
    initialData: { isPro: false }
  });

  const { data: user } = useQuery({
    queryKey: ['current-user'],
    queryFn: () => base44.auth.me(),
  });

  const { data: analyses = [], refetch: refetchAnalyses } = useQuery({
    queryKey: ['scenario-analyses'],
    queryFn: async () => {
      const allAnalyses = await base44.entities.ScenarioAnalysis.list('-created_date');
      const now = new Date();
      return allAnalyses.filter(a => new Date(a.expires_date) > now);
    },
    enabled: subscriptionData.isPro
  });

  // Check if user has already accepted disclaimer
  const { data: userDisclaimers = [] } = useQuery({
    queryKey: ['user-disclaimers', user?.email],
    queryFn: async () => {
      if (!user?.email) return [];
      const allDisclaimers = await base44.entities.DisclaimerAcceptance.list();
      return allDisclaimers.filter(d => d.user_email === user.email);
    },
    enabled: subscriptionData.isPro && !!user?.email
  });

  // Check on component mount if user needs to see first-time disclaimer
  React.useEffect(() => {
    if (subscriptionData.isPro && user?.email && userDisclaimers.length === 0 && !hasAcceptedFirstTime) {
      setShowFirstTimeDisclaimer(true);
    }
  }, [subscriptionData.isPro, user?.email, userDisclaimers, hasAcceptedFirstTime]);

  const createAnalysisMutation = useMutation({
    mutationFn: (data) => base44.entities.ScenarioAnalysis.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['scenario-analyses'] });
      refetchAnalyses();
      setTitle("");
      setScenario("");
      setUploadedFiles([]);
    },
  });

  const createDisclaimerMutation = useMutation({
    mutationFn: (data) => base44.entities.DisclaimerAcceptance.create(data),
  });

  const deleteAnalysisMutation = useMutation({
    mutationFn: (id) => base44.entities.ScenarioAnalysis.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['scenario-analyses'] });
      refetchAnalyses();
    },
  });

  const handleFileUpload = async (e) => {
    const files = Array.from(e.target.files);
    if (files.length === 0) return;

    setUploading(true);
    try {
      const uploadPromises = files.map(file => 
        base44.integrations.Core.UploadFile({ file })
      );
      const results = await Promise.all(uploadPromises);
      const fileUrls = results.map(r => r.file_url);
      setUploadedFiles(prev => [...prev, ...fileUrls]);
    } catch (error) {
      console.error("Upload error:", error);
      alert("Failed to upload files");
    } finally {
      setUploading(false);
    }
  };

  const checkForCriminalContent = (text) => {
    const criminalKeywords = [
      'steal', 'theft', 'robbery', 'murder', 'assault', 'fraud', 'embezzle',
      'illegal drug', 'methamphetamine', 'cocaine', 'heroin',
      'human trafficking', 'kidnap', 'arson', 'bomb', 'explosive',
      'poison person', 'harm person', 'kill person', 'attack person'
    ];
    
    const lowerText = text.toLowerCase();
    return criminalKeywords.some(keyword => lowerText.includes(keyword));
  };

  const handleGenerateAnalysis = async () => {
    if (!title.trim() || !scenario.trim()) {
      alert("Please provide both a title and scenario description");
      return;
    }

    // Check if first-time disclaimer needs to be shown
    if (!hasAcceptedFirstTime && userDisclaimers.length === 0) {
      setPendingAnalysis({ title, scenario, uploadedFiles });
      setShowFirstTimeDisclaimer(true);
      return;
    }

    const containsCriminal = checkForCriminalContent(scenario);
    
    if (containsCriminal) {
      setPendingAnalysis({ title, scenario, uploadedFiles });
      setShowWarningDialog(true);
      return;
    }

    await proceedWithGeneration(false);
  };

  const handleAcceptFirstTimeDisclaimer = async () => {
    try {
      const disclaimerExpiresDate = new Date();
      // If user is subscribed, store indefinitely (far future date)
      // If not subscribed or unsubscribes, will be 1 year from acceptance
      if (subscriptionData.isPro) {
        disclaimerExpiresDate.setFullYear(disclaimerExpiresDate.getFullYear() + 50); // Indefinite
      } else {
        disclaimerExpiresDate.setFullYear(disclaimerExpiresDate.getFullYear() + 1);
      }

      await createDisclaimerMutation.mutateAsync({
        scenario_analysis_id: "first_time_acceptance",
        disclaimer_text: TENNESSEE_DISCLAIMER,
        user_email: user.email,
        acceptance_timestamp: new Date().toISOString(),
        scenario_summary: "Initial disclaimer acceptance for AI Scenario Analysis feature",
        expires_date: disclaimerExpiresDate.toISOString().split('T')[0]
      });

      setHasAcceptedFirstTime(true);
      setShowFirstTimeDisclaimer(false);

      // If there was a pending analysis, continue with it
      if (pendingAnalysis) {
        setTitle(pendingAnalysis.title);
        setScenario(pendingAnalysis.scenario);
        setUploadedFiles(pendingAnalysis.uploadedFiles);
        setPendingAnalysis(null);
        // Recheck for criminal content
        const containsCriminal = checkForCriminalContent(pendingAnalysis.scenario);
        if (containsCriminal) {
          setShowWarningDialog(true);
        } else {
          await proceedWithGeneration(false);
        }
      }
    } catch (error) {
      console.error("Failed to save disclaimer acceptance:", error);
      alert("Failed to save disclaimer acceptance");
    }
  };

  // Fetch advice templates
  const { data: templates = [] } = useQuery({
    queryKey: ['scenario-templates'],
    queryFn: () => base44.entities.ScenarioResponseDB.list(),
    staleTime: 24 * 60 * 60 * 1000, // 24 hours
    gcTime: 7 * 24 * 60 * 60 * 1000, // 7 days
  });

  // Fetch farm profile for context
  const { data: farmProfiles = [] } = useQuery({
    queryKey: ['farm-profile'],
    queryFn: async () => {
      const isAuth = await base44.auth.isAuthenticated();
      if (!isAuth) return [];
      return base44.entities.FarmProfile.list();
    },
    enabled: subscriptionData.isPro,
  });

  const farmProfile = farmProfiles[0] || null;

  const proceedWithGeneration = async (overrodeWarning) => {
    setGenerating(true);
    try {
      // For criminal/warning content, still use minimal LLM response
      if (overrodeWarning) {
        const warningResponse = `## ⚠️ Content Advisory

This scenario contains references to potentially problematic activities.

### Legal & Ethical Considerations
- This type of activity may have legal implications in your jurisdiction
- Consult with appropriate legal professionals before taking any action
- Consider the ethical implications carefully

### Potential Consequences
- Legal liability and potential prosecution
- Civil liability for damages
- Impact on property and business

### Professional Consultation Required
We strongly recommend consulting with:
- A licensed attorney familiar with agricultural and property law
- Local law enforcement for guidance on legal methods
- Professional services if applicable

### Disclaimer
This analysis is for informational purposes only and does not constitute legal advice. You are solely responsible for your actions.`;

        const expiresDate = new Date();
        expiresDate.setDate(expiresDate.getDate() + 10);

        const analysisData = {
          title,
          scenario_description: scenario,
          uploaded_files: uploadedFiles,
          ai_analysis: warningResponse,
          contains_criminal_warning: true,
          user_overrode_warning: true,
          expires_date: expiresDate.toISOString().split('T')[0],
          tags: []
        };

        const createdAnalysis = await createAnalysisMutation.mutateAsync(analysisData);

        const disclaimerExpiresDate = new Date();
        disclaimerExpiresDate.setFullYear(disclaimerExpiresDate.getFullYear() + 1);

        await createDisclaimerMutation.mutateAsync({
          scenario_analysis_id: createdAnalysis.id,
          disclaimer_text: TENNESSEE_DISCLAIMER,
          user_email: user.email,
          acceptance_timestamp: new Date().toISOString(),
          scenario_summary: `${title} - ${scenario.substring(0, 200)}...`,
          expires_date: disclaimerExpiresDate.toISOString().split('T')[0]
        });

        setShowWarningDialog(false);
        setShowDisclaimerDialog(false);
        setPendingAnalysis(null);
        setDisclaimerAccepted(false);
        setGenerating(false);
        return;
      }

      // Use LLM ONLY for keyword extraction and template matching (minimal tokens)
      const matchingPrompt = `Extract 5-10 keywords from this scenario for template matching. Return ONLY a JSON object.

Scenario: "${title} - ${scenario}"

Farm context: ${farmProfile ? `${farmProfile.farm_name}, ${farmProfile.total_acreage} acres, soil types: ${farmProfile.soil_types?.map(s => s.soil_type).join(', ') || 'unknown'}` : 'No farm profile'}

Return JSON format:
{
  "keywords": ["keyword1", "keyword2"],
  "category": "one of: livestock_health, livestock_breeding, livestock_nutrition, predator_control, pest_management, crop_disease, crop_planning, soil_health, water_management, infrastructure, equipment, financial, weather_emergency, processing_butchering, fermentation, dairy, poultry, general",
  "animal_type": "if applicable: chicken, goat, cow, pig, sheep, rabbit, duck, turkey, bee_hive, or null",
  "priority": "low, medium, high, or critical"
}`;

      const matchResult = await base44.integrations.Core.InvokeLLM({
        prompt: matchingPrompt,
        response_json_schema: {
          type: "object",
          properties: {
            keywords: { type: "array", items: { type: "string" } },
            category: { type: "string" },
            animal_type: { type: "string" },
            priority: { type: "string" }
          }
        }
      });

      // Find best matching template
      let bestMatch = null;
      let bestScore = 0;

      for (const template of templates) {
        let score = 0;
        
        // Category match (high weight)
        if (template.category === matchResult.category) score += 10;
        
        // Keyword matches
        const matchedKeywords = matchResult.keywords.filter(kw => 
          template.keywords.some(tk => 
            tk.toLowerCase().includes(kw.toLowerCase()) || 
            kw.toLowerCase().includes(tk.toLowerCase())
          )
        );
        score += matchedKeywords.length * 3;

        // Animal type match
        if (matchResult.animal_type && template.animal_types?.includes(matchResult.animal_type)) {
          score += 5;
        }

        if (score > bestScore) {
          bestScore = score;
          bestMatch = template;
        }
      }

      // Build response from template or fallback
      let finalAdvice;
      if (bestMatch && bestScore >= 5) {
        // Use template content
        finalAdvice = `## ${bestMatch.title}

${bestMatch.advice_content}

${bestMatch.steps?.length > 0 ? `### Step-by-Step Instructions
${bestMatch.steps.map(s => `**${s.step_number}. ${s.title}**\n${s.description}`).join('\n\n')}` : ''}

${bestMatch.warnings?.length > 0 ? `### ⚠️ Important Warnings
${bestMatch.warnings.map(w => `- ${w}`).join('\n')}` : ''}

${bestMatch.when_to_call_vet ? `### When to Seek Professional Help
${bestMatch.when_to_call_vet}` : ''}

${bestMatch.estimated_cost_range ? `### Estimated Cost Range
${bestMatch.estimated_cost_range}` : ''}

${bestMatch.time_to_resolution ? `### Expected Timeline
${bestMatch.time_to_resolution}` : ''}

---
*Template: ${bestMatch.template_id} | Category: ${bestMatch.category}*`;
      } else {
        // No good match - provide generic response
        finalAdvice = `## Analysis: ${title}

### Summary
Based on your scenario description, we've identified this as a **${matchResult.category.replace(/_/g, ' ')}** issue${matchResult.animal_type ? ` related to **${matchResult.animal_type}**` : ''}.

### General Recommendations
1. **Assess the Situation** - Document all relevant details including timing, symptoms, and environmental factors
2. **Research Local Resources** - Contact your local agricultural extension office for region-specific guidance
3. **Consult Professionals** - For health-related issues, consult a licensed veterinarian; for legal matters, consult an attorney
4. **Document Everything** - Keep detailed records for future reference and pattern identification

### Keywords Identified
${matchResult.keywords.map(k => `- ${k}`).join('\n')}

### Priority Level
**${matchResult.priority?.toUpperCase() || 'MEDIUM'}**

### Next Steps
- Review relevant guides in our library for more detailed information
- Consider posting in the community forum for peer advice
- Contact appropriate professionals if situation is urgent

---
*Note: No specific template matched your scenario. Consider refining your description or consulting our guides library.*`;
      }

      const expiresDate = new Date();
      expiresDate.setDate(expiresDate.getDate() + 10);

      const analysisData = {
        title,
        scenario_description: scenario,
        uploaded_files: uploadedFiles,
        ai_analysis: finalAdvice,
        contains_criminal_warning: false,
        user_overrode_warning: false,
        expires_date: expiresDate.toISOString().split('T')[0],
        tags: matchResult.keywords || []
      };

      await createAnalysisMutation.mutateAsync(analysisData);

      setShowWarningDialog(false);
      setShowDisclaimerDialog(false);
      setPendingAnalysis(null);
      setDisclaimerAccepted(false);
    } catch (error) {
      console.error("Generation error:", error);
      alert("Failed to generate analysis. Please try again.");
    } finally {
      setGenerating(false);
    }
  };

  const handlePrintAnalysis = (analysis) => {
    // Create a simple print window instead of using printReport
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to print');
      return;
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${analysis.title}</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            padding: 40px;
            max-width: 800px;
            margin: 0 auto;
            color: #1f2937;
            line-height: 1.6;
          }
          h1 {
            color: #059669;
            margin-bottom: 8px;
          }
          .subtitle {
            color: #6b7280;
            margin-bottom: 24px;
            font-size: 14px;
          }
          .section {
            margin: 24px 0;
            padding: 16px;
            background: #f9fafb;
            border-radius: 8px;
          }
          .section h2 {
            color: #374151;
            font-size: 18px;
            margin-top: 0;
          }
          .content {
            white-space: pre-wrap;
          }
          .warning {
            background: #fef2f2;
            border-left: 4px solid #dc2626;
            padding: 16px;
            margin: 24px 0;
          }
          @media print {
            body { padding: 20px; }
          }
        </style>
      </head>
      <body>
        <h1>${analysis.title}</h1>
        <div class="subtitle">
          Generated on ${format(new Date(analysis.created_date), 'PPP')} • 
          Expires ${format(new Date(analysis.expires_date), 'PPP')}
        </div>
        
        ${analysis.contains_criminal_warning ? `
          <div class="warning">
            <strong>⚠️ Warning Override Record</strong><br>
            This analysis was generated after accepting comprehensive Tennessee law disclaimer.
          </div>
        ` : ''}
        
        <div class="section">
          <h2>Scenario Description</h2>
          <div class="content">${analysis.scenario_description}</div>
        </div>
        
        <div class="section">
          <h2>AI Analysis & Recommendations</h2>
          <div class="content">${analysis.ai_analysis}</div>
        </div>
        
        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px; text-align: center;">
          <p>Generated from Homestead Acres<br>
          <strong>DISCLAIMER:</strong> This analysis is for informational purposes only and does not constitute professional advice.</p>
        </div>
        
        <script>
          window.onload = function() {
            setTimeout(function() {
              window.print();
            }, 250);
          }
        </script>
      </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();

    // Mark as printed
    base44.entities.ScenarioAnalysis.update(analysis.id, { printed: true });
  };

  const getDaysRemaining = (expiresDate) => {
    const now = new Date();
    const expires = new Date(expiresDate);
    const diffTime = expires - now;
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    return diffDays;
  };

  if (!subscriptionData.isPro) {
    return (
      <div className="min-h-screen p-4 md:p-8 pb-32">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center gap-3 mb-8">
            <div className="w-12 h-12 bg-gradient-to-br from-purple-600 to-indigo-600 rounded-xl flex items-center justify-center shadow-lg">
              <Brain className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-3xl md:text-4xl font-bold text-gray-900">AI Scenario Analysis</h1>
              <p className="text-gray-600 mt-1">Get expert guidance on your homesteading challenges</p>
            </div>
          </div>

          <Card className="border-2 border-purple-300 bg-gradient-to-br from-purple-50 via-pink-50 to-purple-50">
            <CardContent className="py-16 text-center">
              <div className="w-24 h-24 mx-auto mb-6 bg-gradient-to-br from-purple-500 to-purple-600 rounded-3xl flex items-center justify-center shadow-2xl">
                <Crown className="w-12 h-12 text-white" />
              </div>
              <h2 className="text-3xl font-bold text-gray-900 mb-3">
                AI Scenario Analysis is a Pro Feature
              </h2>
              <p className="text-lg text-gray-600 mb-8 max-w-2xl mx-auto">
                Get AI-powered analysis and step-by-step guidance for your specific homesteading scenarios
              </p>

              <div className="max-w-md mx-auto mb-8 bg-white rounded-xl p-6 shadow-lg">
                <h3 className="font-semibold text-gray-900 mb-4">With Pro AI Analysis, you get:</h3>
                <ul className="space-y-3 text-left">
                  {[
                    "Unlimited scenario analyses",
                    "Photo and document upload support",
                    "Step-by-step action plans",
                    "Internet-sourced expert knowledge",
                    "10-day analysis retention",
                    "Print-friendly reports",
                    "Livestock, crop, and infrastructure guidance",
                    "Predator control strategies",
                    "Financial planning advice"
                  ].map((feature, idx) => (
                    <li key={idx} className="flex items-start gap-3">
                      <Sparkles className="w-5 h-5 text-purple-600 flex-shrink-0 mt-0.5" />
                      <span className="text-gray-700">{feature}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <Button
                size="lg"
                onClick={() => setShowPaywall(true)}
                className="bg-gradient-to-r from-purple-600 to-purple-700 hover:from-purple-700 hover:to-purple-800 text-lg px-8 py-6"
              >
                <Crown className="w-5 h-5 mr-2" />
                Upgrade to Pro
              </Button>
            </CardContent>
          </Card>

          <PaywallModal
            isOpen={showPaywall}
            onClose={() => setShowPaywall(false)}
            feature="AI Scenario Analysis"
          />
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen p-4 md:p-8 pb-32">
      <div className="max-w-7xl mx-auto space-y-6">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 bg-gradient-to-br from-purple-600 to-indigo-600 rounded-xl flex items-center justify-center shadow-lg">
            <Brain className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-3xl md:text-4xl font-bold text-gray-900">AI Scenario Analysis</h1>
            <p className="text-gray-600 mt-1">Expert guidance for your homesteading challenges</p>
          </div>
        </div>

        <Card className="border-2 border-orange-300 bg-orange-50">
          <CardContent className="py-4">
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-6 h-6 text-orange-600 flex-shrink-0 mt-0.5" />
              <div>
                <p className="font-bold text-orange-900 text-lg mb-2">
                  IMPORTANT DISCLAIMER
                </p>
                <p className="text-sm text-orange-800">
                  <strong>All scenario analyses are for informational and educational purposes ONLY.</strong> This tool does NOT provide professional veterinary, legal, financial, or medical advice. Always consult with licensed professionals before taking action. You are solely responsible for your decisions and actions. Analyses are retained for 10 days only - print important information promptly.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="grid lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2 space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Sparkles className="w-5 h-5 text-purple-600" />
                  Generate New Analysis
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label htmlFor="title">Scenario Title *</Label>
                  <Input
                    id="title"
                    placeholder="e.g., Coyote attacking chickens, Sick goat diagnosis, Orchard planning"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                  />
                </div>

                <div>
                  <Label htmlFor="scenario">Detailed Scenario Description *</Label>
                  <Textarea
                    id="scenario"
                    placeholder="Describe your situation in detail. Include symptoms, timeline, what you've tried, environmental factors, and any other relevant information. The more detail you provide, the better the analysis."
                    value={scenario}
                    onChange={(e) => setScenario(e.target.value)}
                    rows={8}
                    className="resize-none"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    Be specific and thorough. Include photos if helpful.
                  </p>
                </div>

                <div>
                  <Label>Upload Photos or Documents (Optional)</Label>
                  <div className="mt-2">
                    <label className="flex items-center justify-center w-full px-4 py-6 border-2 border-dashed border-gray-300 rounded-lg cursor-pointer hover:border-purple-400 hover:bg-purple-50 transition-colors">
                      <div className="flex flex-col items-center">
                        {uploading ? (
                          <>
                            <Upload className="w-8 h-8 text-purple-600 animate-pulse mb-2" />
                            <span className="text-sm text-purple-600">Uploading...</span>
                          </>
                        ) : (
                          <>
                            <Camera className="w-8 h-8 text-gray-400 mb-2" />
                            <span className="text-sm text-gray-600">Click to upload photos/documents</span>
                            <span className="text-xs text-gray-500 mt-1">JPG, PNG, PDF supported</span>
                          </>
                        )}
                      </div>
                      <input
                        type="file"
                        className="hidden"
                        accept="image/*,.pdf"
                        multiple
                        onChange={handleFileUpload}
                        disabled={uploading}
                      />
                    </label>
                  </div>

                  {uploadedFiles.length > 0 && (
                    <div className="mt-3 space-y-2">
                      {uploadedFiles.map((fileUrl, idx) => (
                        <div key={idx} className="flex items-center justify-between bg-gray-50 p-2 rounded">
                          <span className="text-sm text-gray-700">File {idx + 1}</span>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => setUploadedFiles(prev => prev.filter((_, i) => i !== idx))}
                          >
                            <X className="w-4 h-4" />
                          </Button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                <Button
                  onClick={handleGenerateAnalysis}
                  disabled={generating || !title.trim() || !scenario.trim()}
                  className="w-full bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700"
                  size="lg"
                >
                  {generating ? (
                    <>
                      <Sparkles className="w-5 h-5 mr-2 animate-spin" />
                      Generating Analysis...
                    </>
                  ) : (
                    <>
                      <Brain className="w-5 h-5 mr-2" />
                      Generate AI Analysis
                    </>
                  )}
                </Button>

                <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                  <div className="flex items-start gap-2">
                    <Shield className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
                    <div className="text-sm text-blue-800">
                      <p className="font-semibold mb-1">Your analyses are retained for 10 days</p>
                      <p>Make sure to print or save any important information within this period. After 10 days, analyses are automatically deleted.</p>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          <div>
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Recent Analyses</CardTitle>
              </CardHeader>
              <CardContent>
                {analyses.length === 0 ? (
                  <div className="text-center py-8">
                    <FileText className="w-12 h-12 text-gray-400 mx-auto mb-3" />
                    <p className="text-sm text-gray-600">No analyses yet</p>
                  </div>
                ) : (
                  <div className="space-y-3 max-h-[600px] overflow-y-auto">
                    {analyses.map(analysis => {
                      const daysRemaining = getDaysRemaining(analysis.expires_date);
                      const isExpiringSoon = daysRemaining <= 3;
                      
                      return (
                        <div
                          key={analysis.id}
                          className="p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors cursor-pointer"
                          onClick={() => setSelectedAnalysis(analysis)}
                        >
                          <div className="flex items-start justify-between gap-2">
                            <div className="flex-1 min-w-0">
                              <h4 className="font-semibold text-sm text-gray-900 truncate">
                                {analysis.title}
                              </h4>
                              <p className="text-xs text-gray-500 mt-1">
                                {format(new Date(analysis.created_date), 'MMM d, yyyy')}
                              </p>
                              <div className="flex items-center gap-2 mt-2">
                                <Badge className={`text-xs ${isExpiringSoon ? 'bg-orange-100 text-orange-700' : 'bg-blue-100 text-blue-700'}`}>
                                  <Clock className="w-3 h-3 mr-1" />
                                  {daysRemaining} days left
                                </Badge>
                                {analysis.contains_criminal_warning && (
                                  <Badge className="text-xs bg-red-100 text-red-700">
                                    <AlertTriangle className="w-3 h-3 mr-1" />
                                    Warning
                                  </Badge>
                                )}
                              </div>
                            </div>
                            <div className="flex flex-col gap-1">
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  handlePrintAnalysis(analysis);
                                }}
                              >
                                <Printer className="w-4 h-4" />
                              </Button>
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  if (confirm('Delete this analysis?')) {
                                    deleteAnalysisMutation.mutate(analysis.id);
                                  }
                                }}
                              >
                                <Trash2 className="w-4 h-4 text-red-600" />
                              </Button>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>

        <Dialog open={showWarningDialog} onOpenChange={setShowWarningDialog}>
          <DialogContent className="max-w-2xl">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2 text-red-700">
                <AlertTriangle className="w-6 h-6" />
                Potentially Problematic Content Detected
              </DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              <div className="bg-red-50 border-2 border-red-300 rounded-lg p-4">
                <p className="text-red-900 font-semibold mb-2">
                  WARNING: Your scenario description may contain references to illegal or harmful activities.
                </p>
                <p className="text-red-800 text-sm">
                  This AI tool is designed for legitimate homesteading, farming, and property management guidance. 
                  If you proceed, you will receive ANALYTICAL COMMENTARY ONLY - not instructions or tactical advice.
                </p>
              </div>

              <div className="bg-gray-50 border border-gray-300 rounded-lg p-4">
                <p className="text-sm text-gray-700 mb-3">
                  <strong>Legitimate farming activities we CAN help with include:</strong>
                </p>
                <ul className="text-sm text-gray-600 space-y-1 list-disc list-inside">
                  <li>Predator control (coyotes, foxes, raccoons)</li>
                  <li>Livestock processing and butchering</li>
                  <li>Pest elimination (rodents, insects)</li>
                  <li>Property defense against animals</li>
                  <li>Humane animal euthanasia</li>
                  <li>Farm infrastructure and planning</li>
                </ul>
              </div>

              <p className="text-sm text-gray-700">
                If your scenario involves <strong>criminal activity targeting people</strong> (theft, assault, illegal drugs, fraud, etc.), 
                you may proceed but will only receive risk analysis - not actionable guidance.
              </p>
            </div>

            <DialogFooter className="flex-col sm:flex-row gap-3">
              <Button
                variant="outline"
                onClick={() => {
                  setShowWarningDialog(false);
                  setPendingAnalysis(null);
                }}
                className="w-full sm:w-auto"
              >
                Cancel
              </Button>
              <Button
                onClick={() => {
                  setShowWarningDialog(false);
                  setShowDisclaimerDialog(true);
                }}
                className="w-full sm:w-auto bg-orange-600 hover:bg-orange-700"
              >
                I Understand - Show Disclaimer
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        <Dialog open={showDisclaimerDialog} onOpenChange={setShowDisclaimerDialog}>
          <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2 text-red-700">
                <Shield className="w-6 h-6" />
                COMPREHENSIVE LIABILITY DISCLAIMER - Tennessee Law
              </DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              <div className="bg-red-50 border-2 border-red-400 rounded-lg p-4">
                <p className="text-red-900 font-bold text-center">
                  YOU MUST READ AND ACCEPT THIS DISCLAIMER TO PROCEED
                </p>
              </div>

              <div className="bg-white border border-gray-300 rounded-lg p-6 max-h-96 overflow-y-auto text-sm whitespace-pre-wrap font-mono">
                {TENNESSEE_DISCLAIMER}
              </div>

              <div className="flex items-start gap-3 bg-gray-50 border border-gray-300 rounded-lg p-4">
                <Checkbox
                  id="accept-disclaimer"
                  checked={disclaimerAccepted}
                  onCheckedChange={setDisclaimerAccepted}
                />
                <label htmlFor="accept-disclaimer" className="text-sm text-gray-700 cursor-pointer">
                  <strong>I have read, understood, and agree to be bound by all terms of this disclaimer.</strong>
                  <br />
                  I acknowledge that Tennessee State Law will govern any disputes and that my acceptance will be recorded for one (1) year.
                  <br />
                  I accept full responsibility for any actions I take based on the analysis provided.
                </label>
              </div>
            </div>

            <DialogFooter className="flex-col sm:flex-row gap-3">
              <Button
                variant="outline"
                onClick={() => {
                  setShowDisclaimerDialog(false);
                  setDisclaimerAccepted(false);
                  setPendingAnalysis(null);
                }}
                className="w-full sm:w-auto"
              >
                Decline & Cancel
              </Button>
              <Button
                onClick={() => proceedWithGeneration(true)}
                disabled={!disclaimerAccepted || generating}
                className="w-full sm:w-auto bg-red-600 hover:bg-red-700"
              >
                {generating ? (
                  <>
                    <Sparkles className="w-5 h-5 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <CheckCircle2 className="w-5 h-5 mr-2" />
                    I Accept and Proceed
                  </>
                )}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* First-Time Disclaimer Dialog */}
        <Dialog open={showFirstTimeDisclaimer} onOpenChange={(open) => {
          if (!open) {
            setShowFirstTimeDisclaimer(false);
            setPendingAnalysis(null);
          }
        }}>
          <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2 text-red-700">
                <Shield className="w-6 h-6" />
                AI Scenario Analysis - Required Disclaimer
              </DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              <div className="bg-orange-50 border-2 border-orange-400 rounded-lg p-4">
                <p className="text-orange-900 font-bold text-center">
                  Before using AI Scenario Analysis, you must read and accept this disclaimer
                </p>
              </div>

              <div className="bg-white border border-gray-300 rounded-lg p-6 max-h-96 overflow-y-auto text-sm whitespace-pre-wrap font-mono">
                {TENNESSEE_DISCLAIMER}
              </div>

              <div className="flex items-start gap-3 bg-gray-50 border border-gray-300 rounded-lg p-4">
                <Checkbox
                  id="accept-first-time"
                  checked={disclaimerAccepted}
                  onCheckedChange={setDisclaimerAccepted}
                />
                <label htmlFor="accept-first-time" className="text-sm text-gray-700 cursor-pointer">
                  <strong>I have read, understood, and agree to be bound by all terms of this disclaimer.</strong>
                  <br />
                  I acknowledge that Tennessee State Law will govern any disputes and that my acceptance will be recorded.
                  <br />
                  I accept full responsibility for any actions I take based on analyses provided.
                </label>
              </div>
            </div>

            <DialogFooter className="flex-col sm:flex-row gap-3">
              <Button
                variant="outline"
                onClick={() => {
                  setShowFirstTimeDisclaimer(false);
                  setDisclaimerAccepted(false);
                  setPendingAnalysis(null);
                }}
                className="w-full sm:w-auto"
              >
                Decline & Exit
              </Button>
              <Button
                onClick={handleAcceptFirstTimeDisclaimer}
                disabled={!disclaimerAccepted}
                className="w-full sm:w-auto bg-green-600 hover:bg-green-700"
              >
                <CheckCircle2 className="w-5 h-5 mr-2" />
                I Accept and Continue
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        <Dialog open={!!selectedAnalysis} onOpenChange={() => setSelectedAnalysis(null)}>
          <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
            {selectedAnalysis && (
              <>
                <DialogHeader>
                  <DialogTitle className="text-xl">{selectedAnalysis.title}</DialogTitle>
                  <div className="flex items-center gap-2 mt-2">
                    <Badge variant="outline">
                      {format(new Date(selectedAnalysis.created_date), 'PPP')}
                    </Badge>
                    <Badge className="bg-blue-100 text-blue-700">
                      <Clock className="w-3 h-3 mr-1" />
                      Expires in {getDaysRemaining(selectedAnalysis.expires_date)} days
                    </Badge>
                    {selectedAnalysis.contains_criminal_warning && (
                      <Badge className="bg-red-100 text-red-700">
                        <AlertTriangle className="w-3 h-3 mr-1" />
                        Warning Override
                      </Badge>
                    )}
                  </div>
                </DialogHeader>
                <div className="space-y-4">
                  <div>
                    <h3 className="font-semibold text-gray-900 mb-2">Your Scenario:</h3>
                    <div className="bg-gray-50 rounded-lg p-4 text-sm text-gray-700 whitespace-pre-wrap">
                      {selectedAnalysis.scenario_description}
                    </div>
                  </div>

                  {selectedAnalysis.uploaded_files && selectedAnalysis.uploaded_files.length > 0 && (
                    <div>
                      <h3 className="font-semibold text-gray-900 mb-2">Uploaded Files:</h3>
                      <div className="grid grid-cols-2 gap-2">
                        {selectedAnalysis.uploaded_files.map((fileUrl, idx) => (
                          <a
                            key={idx}
                            href={fileUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-sm text-blue-600 hover:underline"
                          >
                            View File {idx + 1}
                          </a>
                        ))}
                      </div>
                    </div>
                  )}

                  <div>
                    <h3 className="font-semibold text-gray-900 mb-2">AI Analysis & Recommendations:</h3>
                    <div className="bg-purple-50 border border-purple-200 rounded-lg p-4 text-sm text-gray-700 whitespace-pre-wrap">
                      {selectedAnalysis.ai_analysis}
                    </div>
                  </div>

                  {selectedAnalysis.contains_criminal_warning && (
                    <div className="bg-red-50 border-2 border-red-300 rounded-lg p-4">
                      <div className="flex items-start gap-2">
                        <AlertTriangle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
                        <div className="text-sm text-red-800">
                          <p className="font-semibold mb-1">Warning Override Record</p>
                          <p>You accepted the comprehensive Tennessee law disclaimer to view this analysis. This acceptance has been recorded for one year.</p>
                        </div>
                      </div>
                    </div>
                  )}
                </div>

                <DialogFooter className="flex-col sm:flex-row gap-3">
                  <Button
                    variant="outline"
                    onClick={() => setSelectedAnalysis(null)}
                    className="w-full sm:w-auto"
                  >
                    Close
                  </Button>
                  <Button
                    onClick={() => handlePrintAnalysis(selectedAnalysis)}
                    className="w-full sm:w-auto bg-blue-600 hover:bg-blue-700"
                  >
                    <Printer className="w-5 h-5 mr-2" />
                    Print Analysis
                  </Button>
                </DialogFooter>
              </>
            )}
          </DialogContent>
        </Dialog>
      </div>
    </div>
  );
}