
// No jsPDF imports needed as we are using native browser functionality
// import jsPDF from "jspdf";
// import "jspdf-autotable";

// Universal print utility for reports using browser's native print functionality
// This function will open a print dialog, allowing the user to print to a physical printer
// or save as a PDF using the browser's built-in "Save as PDF" option.
export const printReport = (reportData) => {
  const { title, subtitle, data, columns } = reportData; // fileName and orientation are not directly used here as the browser handles saving/printing.
  
  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        @media print {
          body { margin: 0; padding: 20px; }
          .no-print { display: none; }
        }
        body { font-family: Arial, sans-serif; }
        h1 { color: #16a34a; font-size: 24px; margin-bottom: 5px; }
        h2 { color: #666; font-size: 14px; margin-top: 0; }
        .meta { color: #999; font-size: 12px; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #16a34a; color: white; padding: 8px; text-align: left; font-size: 12px; }
        td { border: 1px solid #ddd; padding: 6px; font-size: 11px; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 10px; color: #999; }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      ${subtitle ? `<h2>${subtitle}</h2>` : ''}
      <div class="meta">Generated by Homestead Acres on ${new Date().toLocaleDateString()}</div>
  `;

  if (data && columns) {
    html += '<table><thead><tr>';
    columns.forEach(col => {
      html += `<th>${col.label || col}</th>`;
    });
    html += '</tr></thead><tbody>';

    data.forEach(row => {
      html += '<tr>';
      columns.forEach(col => {
        const key = col.key || col;
        const value = row[key];
        // Ensure that 0 or false are displayed, not treated as empty.
        const displayValue = col.format ? col.format(value, row) : (value !== null && value !== undefined ? value : "");
        html += `<td>${displayValue}</td>`;
      });
      html += '</tr>';
    });

    html += '</tbody></table>';
  }

  html += `
      <div class="footer">
        <p>Report generated by Homestead Acres</p>
        <p>For questions or support, visit homesteadacres.app</p>
      </div>
    </body>
    </html>
  `;

  // Open print dialog
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  } else {
    // Fallback if window.open is blocked by a popup blocker
    console.error('Failed to open print window. Popup blockers might be preventing it.');
    alert('Please allow pop-ups for this site to print the report.');
  }
};

// Export to Word (HTML format)
export const exportToWord = (reportData) => {
  const { title, subtitle, data, columns, fileName } = reportData;
  
  let html = `
    <!DOCTYPE html>
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset="utf-8">
      <title>${title}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { color: #16a34a; border-bottom: 2px solid #16a34a; padding-bottom: 10px; }
        h2 { color: #666; font-size: 14px; }
        .meta { color: #999; font-size: 12px; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #16a34a; color: white; padding: 10px; text-align: left; }
        td { border: 1px solid #ddd; padding: 8px; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 10px; color: #999; }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      ${subtitle ? `<h2>${subtitle}</h2>` : ''}
      <div class="meta">
        <p>Generated by Homestead Acres on ${new Date().toLocaleDateString()}</p>
      </div>
  `;

  if (data && columns) {
    html += '<table><thead><tr>';
    columns.forEach(col => {
      html += `<th>${col.label || col}</th>`;
    });
    html += '</tr></thead><tbody>';

    data.forEach(row => {
      html += '<tr>';
      columns.forEach(col => {
        const key = col.key || col;
        const value = row[key];
        // Ensure that 0 or false are displayed, not treated as empty.
        const displayValue = col.format ? col.format(value, row) : (value !== null && value !== undefined ? value : "");
        html += `<td>${displayValue}</td>`;
      });
      html += '</tr>';
    });

    html += '</tbody></table>';
  }

  html += `
      <div class="footer">
        <p>Report generated by Homestead Acres</p>
        <p>For questions or support, visit homesteadacres.app</p>
      </div>
    </body>
    </html>
  `;

  // Create blob and download
  // Add Byte Order Mark (BOM) for better Word compatibility
  const blob = new Blob(['\ufeff', html], { 
    type: 'application/msword' 
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${fileName || "report"}-${new Date().toISOString().split('T')[0]}.doc`;
  
  // Appending and removing the link from the document body ensures cross-browser compatibility
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Print to physical printer (same as printReport, leveraging browser's print functionality)
export const printToPhysical = (reportData) => {
  printReport(reportData);
};

// Export as PDF via browser print dialog (same as printReport, as browser print dialogs often include "Save as PDF" option)
export const exportToPDF = (reportData) => {
  printReport(reportData);
};
